#!/c/Python34x32/python.exe

import signal
from gi.repository import Gtk
from lib.Handler import Handler

max_int = 2**14 # 16384

builder = Gtk.Builder()
builder.add_from_file("ui/crowbar.glade")
builder.connect_signals(Handler())

window = builder.get_object("MainWindow")
window.show_all()

signal.signal(signal.SIGINT, signal.SIG_DFL)
Gtk.main()
