#!/usr/bin/env python2

import signal

from gi.repository import Gtk

import linkedpanes

def main():

    if 'gtk':
        win = Gtk.Window()
        win.set_size_request(300, 200)
        win.connect("delete-event", Gtk.main_quit)

        if 'linkedpanes':
            _linkedpanes = linkedpanes.LinkedPanes(
                Gtk.Label('viewport'), Gtk.Label('TOP'),
                Gtk.Label('LEFT'), Gtk.Label('FRONT'),
            )
            win.add(_linkedpanes)

        win.show_all()
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        Gtk.main()


if __name__ == '__main__':
    main()
