#!/usr/bin/env python2

import signal

from gi.repository import Gtk

GEOMETRY = list()
GEOMETRY.append(dict(x=-1, y=-1, z=-1, w=2, l=2, h=2))

import dictview

def main():

    if 'gtk':
        win = Gtk.Window()
        win.set_size_request(300, 200)
        win.connect("delete-event", Gtk.main_quit)
        win.add(dictview.DictView(GEOMETRY))
        win.show_all()
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        Gtk.main()


if __name__ == '__main__':
    main()
