#!/usr/bin/env python2

import signal

from gi.repository import Gtk

import dictview
import linkedpanes

GEOMETRY = list()
GEOMETRY.append(dict(x=(-33, 33), y=(-33, 33), z=(-33, 33)))

DEFAULT_SCROLL_LOCK = True

def main():

    if 'gtk':
        win = Gtk.Window()
        win.set_size_request(300, 200)
        win.connect("delete-event", Gtk.main_quit)

        if 'linkedpanes':
            pane_data = {
                'geometry': GEOMETRY,
                'scroll_lock': {
                    'enabled': DEFAULT_SCROLL_LOCK,
                    'x': Gtk.Adjustment(),
                    'y': Gtk.Adjustment(),
                    'z': Gtk.Adjustment(),
                },
            }
            _linkedpanes = linkedpanes.LinkedPanes(
                Gtk.Label('Viewport'),
                dictview.DictView(('y', 'x'), **pane_data),
                dictview.DictView(('x', 'z'), **pane_data),
                dictview.DictView(('y', 'z'), **pane_data),
            )
            win.add(_linkedpanes)

        win.show_all()
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        Gtk.main()


if __name__ == '__main__':
    main()
