#!/usr/bin/env python

import subprocess
import os
import signal

COMMAND = [
    'blender',
    # '--background',
    'blank.blend',
    '--python',
    'bpy_vmf.py'
]

def main(command):
    try:
        process = subprocess.Popen(command)
        process.wait()
        print process.returncode
    except KeyboardInterrupt:
        # Kill, KIIIILLLLL
        # http://stackoverflow.com/a/4676732/1695680
        os.kill(process.pid, signal.SIGTERM)

if __name__ == '__main__':
    main(COMMAND)
